#
# Cluster mini - provisioning playbook
#
---
- name: Provision nodes
  hosts: ec2
  sudo: yes
  gather_facts: yes
  roles:
  - role: common
  - role: hadoop


- name: Provision zookeeper
  hosts: zookeeper
  sudo: yes
  gather_facts: no
  roles:
  - role: zookeeper
